### ISSUE TITLE
Allow for deep merge on index YAML files

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/corgi#104]
Currently if you have the following in your `index.yml` file…
```yaml
footer:
  logo: "my-logo.png"
  alt: "Company Name logo"
```

You cannot inherit those nested properties in a locale YAML file like so:
```yaml
# en-us.yml

footer:
  legal: © 2024 Some Company. All rights reserved.
  # logo not inherited
  # alt not inherited 
```
